#!/bin/sh
set -e
git describe --abbrev=8 --dirty | sed 's/v\([^-]*\)-\([^-]*\)-\(.*\)/\1.dev\2.\3/' > version
cat version
echo "# osmo-gsm-tester version.
# Automatically generated by update_version.sh.
# Gets imported by __init__.py.

_version = '$(cat version)'" \
  > src/osmo_gsm_tester/_version.py
